SHOW DATABASES;

USE PROJETO;

SHOW TABLES;

SELECT * FROM CLIENTE c  ;

/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'F';

/* NÃO FUNCIONA ASSIM */
SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE EMAIL = NULL;

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE IS NULL;

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/* IS NULL OU IS NOT NULL */

/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL 
FROM CLIENTE;

UPDATE CLIENTE 
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL 
FROM CLIENTE;

/* WHERE VAI SER O SEU MELHOR AMIGO DA VIDA PARA VIDA INTEIRA */

SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

SELECT * FROM CLIENTE
WHERE NOME = 'JOAO';

UPDATE CLIENTE 
SET EMAIL = 'JOAO@IG.COM.BR'
WHERE NOME = 'JOAO';

UPDATE CLIENTE 
SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

UPDATE CLIENTE 
SET EMAIL = 'CARLA@IG.COM.BR'
WHERE NOME = 'CARLA';

/* COMMIT E ROLLBACK VOLTA ESTADOS DO BANCO */

/* DELETANDO REGISTROS COM A CLAUSULA DELETE */

DELETE FROM CLIENTE ;

SELECT COUNT(*) FROM CLIENTE; 

SELECT * FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; 

SELECT 6 * 1 - 3 + 10 * 0;

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES 
('CARLA', 'F', 'C.LOPES@UOL.COM', 456312789, '23658970', 'RUA COPPER LEAF - WILLIAMBURG - KITCHENER');

SELECT * FROM CLIENTE 
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';

DELETE FROM CLIENTE 
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT * FROM CLIENTE;

/* ENTRANDO COM MAIS TELEFONES */

UPDATE CLIENTE
SET TELEFONE = '22923110 - 97865434'
WHERE NOME = 'JOÃO';

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE
GROUP BY ENDERECO ;

INSERT INTO CLIENTE VALUES
('CARLA', 'F', 'C.LOPES@UOL.COM', 456312789, '9301-7585', 'RUA COPPER LEAF - WILLIAMBURG - KITCHENER');

SELECT SEXO, COUNT(*) AS QTD FROM CLIENTE
GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL */

/*
1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA.
OU QUANDO O CAMPO FOR DIVISÍVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
TODO O REGISTRO COMO SENDO UNICO.
ISSO É O QUE CHAMAMOS DE CHAVE PRIMÁRIA OU PRIMARY KEY.

HÁ DOIS TIPOS DE CHAVES
- NATURAL: PERTENCE AO REGISTRO COMO CPF, CNPJ
- ARTIFICIAL: VOCÊ ADICIONA AO REGISTRO PARA IDENTIFICA-LO

 */

/* CARDINALIDADE */

/* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIOS */

/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE 
 0 - NÃO OBRIGATÓRIO
 1 - OBRIGATÓRIO
 
 SEGUNDO ALGARISMO - CARDINALIDADE
 1 - MÁXIMO DE UM
 N - MAIS DE UM
 */

CREATE DATABASE COMERCIO;

USE COMERCIO;

DROP TABLE CLIENTE;

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

DESC CLIENTE;

DROP TABLE ENDERECO;

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO char(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);

DESC ENDERECO;

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);

DESC TELEFONE;

SHOW TABLES;

/* ENDEREÇO É OBRIGATÓRIO
 CADASTRO DE SOMENTO UM. 
 TELEFONE - NÃO É OBRIGATÓRIO;
 CADASTRO DE MAIS DE UM (OPCIONAL) */

/*
 CHAVE ESTRANGEIRA É A PRIMARY KEY DE UMA TABELA 
 QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERÊNCIAS
 ENTRE REGISTROS
 */

/* EM UM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA)
   EM UM RELACIONAMENTO 1 X N A CHAVE ESTRAGEIRA FICA SEMPRE NA CARDINALIDADE N 
*/

INSERT INTO CLIENTE VALUES (NULL, 'JOAO', 'M', 'JOAO@IG.COM', '12345678945');
INSERT INTO CLIENTE VALUES (NULL, 'CARLOS', 'M', 'CARLOS@IG.COM', '34589672631');
INSERT INTO CLIENTE VALUES (NULL, 'ANA', 'F', 'ANA@IG.COM', '487965874123');
INSERT INTO CLIENTE VALUES (NULL, 'CLARA', 'F', NULL, '986248635798');
INSERT INTO CLIENTE VALUES (NULL, 'JORGE', 'M', 'JORGE@IG.COM', '12647954785');
INSERT INTO CLIENTE VALUES (NULL, 'CELIA', 'F', 'CELIA@IG.COM', '65894236871');

SELECT * FROM CLIENTE;

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA CAPITAO HERMES', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA PRES VARGAS', 'JARDINS', 'SAO PAULO', 'SP', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DO OUVIDOR', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA URUGUAIANA', 'CENTRO', 'VITORIA', 'ES', 5);
 
SELECT * FROM ENDERECO;

DESC TELEFONE;

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '78458743', 5);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '56565565', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '12345689', 1);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '12387933', 2);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '12487963', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '15489963', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '48996632', 3);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '78332459', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '12345678', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '98746622', 2);

SELECT * FROM TELEFONE;