SHOW DATABASES;

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE TABELA (
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

DESC TABELA;

-- ADICIONANDO UM PK
ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1);

DESC TABELA;

-- ADICIONANDO UMA COLUNA SEM POSICAO, ULTIMA POSICAO
ALTER TABLE TABELA
ADD COLUNA VARCHAR(30);

ALTER TABLE TABELA
ADD COLUNA100 INT;

DESC TABELA;

-- ADICIONANDO UMA COLUNA COM POSICAO
ALTER TABLE TABELA
ADD COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

DESC TABELA;

-- MODIFICAR O TIPO DE UM CAMPO
ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;

DESC TABELA;

-- ALTERANDO NOE DA TABELA
ALTER TABLE TABELA
RENAME PESSOA;

SHOW TABLES;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

-- FOREIGN KEY
ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

DESC TIME;

/* VERIFICAR AS CHAVES */
SHOW CREATE TABLE TIME;

-- ORGANIZACAO DE CHAVES - CONSTRAINTS (REGRA)

CREATE TABLE JOGADOR(
	IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

DROP TABLE TIME;

CREATE TABLE TIMES(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR(30),
	ID_JOGADOR INT,
	FOREIGN KEY (ID_JOGADOR)
	REFERENCES JOGADOR(IDJOGADOR)
);

INSERT INTO JOGADOR VALUES (NULL, 'GUERRERO');

INSERT INTO TIMES VALUES (NULL, 'FLAMENGO', 1);

SHOW CREATE TABLE JOGADOR;

SHOW CREATE TABLE TIMES;

SHOW DATABASES;

/* ORGANIZANDO CHAVES
   E AÇÕES DE CONSTRAINTS */

SHOW TABLES;

DROP TABLE CLIENTES;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

DESC CLIENTE;

CREATE TABLE TELEFONE(
-- 	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE TELEFONE;

/* DICIONARIO DE DADOS */

SHOW DATABASES;

USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS ;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
	   TABLE_NAME AS "TABELA",
	   CONSTRAINT_NAME AS "NOME DA REGRA",
	   CONSTRAINT_TYPE AS "TIPO"
FROM TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'COMERCIO';

/* APAGANDO CONSTRAINTS */
USE COMERCIO;

ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE; 