USE COMERCIO;

/* SELEÇÃO, PROJEÇÃO E JUNÇÃO */

/* PROJEÇÃO -> É TUDO QUE VAI SER MOSTRADO NA TELA */

SELECT TIPO, NUMERO FROM TELEFONE;

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;

/* SELEÇÃO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
   A CLAUSULA DE SELEÇÃO É O WHERE */

SELECT NOME, SEXO, EMAIL /* PROJEÇÃO */
FROM CLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */

SELECT NUMERO /* PROJEÇÃO */
FROM TELEFONE
WHERE TIPO = 'CEL'; /* SELEÇÃO */

/* JUNÇÃO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

/* ERRADO -> NÃO USAR*/
SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F'; /*JUNCAO*/

/* MODO CERTO DE FAZER */
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON ID_CLIENTE = IDCLIENTE; 

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM*/
	INNER JOIN ENDERECO /*JUNÇÃO*/
	ON ID_CLIENTE = IDCLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */

/* NOME, SEXO, EMAIL, TIPO, NUMERO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
	INNER JOIN TELEFONE
	ON ID_CLIENTE = IDCLIENTE;

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO*/
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
	INNER JOIN ENDERECO
	ON ID_CLIENTE = CLIENTE.IDCLIENTE 
	INNER JOIN TELEFONE
	ON TELEFONE.ID_CLIENTE = CLIENTE.IDCLIENTE ;

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON E.ID_CLIENTE = C.IDCLIENTE 
	INNER JOIN TELEFONE T
	ON T.ID_CLIENTE = C.IDCLIENTE ;

/*
	CATEGORIAS DO SQL
	
	DML - DATA MANIPULATION LANGUAGE - MANIPULAÇÃO DE DADOS
	DDL - DATA DEFINITION LANGUAGE - TIPAGEM DE DADOS
	DCL - DATA CONTROL LANGUAGE - CONTROLE DE ACESSO AOS DADOS
	TCL - TRANSACTION CONTROL LANGUAGE - CONTROLE DE TRANSAÇÃO, PARA ATOMACIDADE
*/

/* DML */

/* INSERT */
INSERT INTO CLIENTE VALUES (NULL, 'PAULA', 'M', NULL, '987456589');
INSERT INTO ENDERECO VALUES (NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NOTEROI', 'RJ', 7);

/* FILTROS */
SELECT * FROM CLIENTE C 
WHERE C.SEXO = 'M';

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

SELECT * FROM CLIENTE;

/* UPDATE */
UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

/* DELETE */
INSERT INTO CLIENTE VALUES (NULL, 'XXX', 'M', NULL, 'XXXXXXXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE
WHERE IDCLIENTE = 8;

SELECT * FROM CLIENTE c ;

/* 
DDL - DATA DEFINITION LANGUAGE
*/

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

SHOW TABLES;

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA */

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

DESC PRODUTO;

/* MODIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO 
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

DESC PRODUTO;

/* ADICIONANDO COLUNA */

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL;

DESC PRODUTO;

/* APAGANDO UMA COLUNA */
ALTER TABLE PRODUTO 
DROP COLUMN PESO;

DESC PRODUTO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA */

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

DESC PRODUTO;

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;

DESC PRODUTO;