SHOW DATABASES;

USE COMERCIO;

/* DELIMITADOR ; 
NO CASO É O PONTO E VÍRGULA
 */

DELIMITER $

SELECT 
	C.NOME, 
	C.SEXO, 
	IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY;

SELECT 'NOME';

/* STORAGE PROCEDURES */

SELECT 'MAFRA';

CREATE PROCEDURE NOME()
BEGIN
	
	/* QUALQUER PROGRAMAÇÃO */
	
END

CREATE PROCEDURE NOME_EMPRESA()
BEGIN
	SELECT 'UNIVERDADE DOS DADOS' AS EMPRESA;
END

/* CHAMANDO PROCEDURE */

CALL NOME_EMPRESA();

/* PROCEDURES COM PARAMETROS */

SELECT 10 * 10 AS CONTA;

CREATE PROCEDURE CONTA()
BEGIN
	SELECT 10 + 10 AS CONTA;
END

CALL CONTA();

DROP PROCEDURE CONTA;

CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
	SELECT NUMERO1 + NUMERO2 AS CONTA;
END

CALL CONTA(100,50);
CALL CONTA(345634,4354);
CALL CONTA(55654,56760);
CALL CONTA(45646,6766);

/* RECAP */

CREATE DATABASE MAFRA;

USE MAFRA;

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

SHOW TABLES;

SHOW DATABASES;

/* PROCEDURES */

USE PROJETO;

CREATE TABLE CURSOS(
	ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

SHOW TABLES;

INSERT INTO CURSOS VALUES
	(NULL, 'JAVA', 30, 500.00),
	(NULL, 'FUNDAMENTOS DE BANCOS DE DADOS', 40, 700.00);

SELECT * FROM CURSOS;

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), 
						   P_HORAS INT(3), 
						   P_VALOR FLOAT(10,2))
BEGIN
	
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);
	
END

CALL CAD_CURSO('BI SQL SERVER', 35, 3000.00);
CALL CAD_CURSO('POWER BI', 20, 1000.00);
CALL CAD_CURSO('TABLEAU', 20, 1200.00);

SELECT * FROM CURSOS;

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

CREATE PROCEDURE CONSULTA_CURSO(NOME VARCHAR(30))
BEGIN
	SELECT ID_CURSO, NOME, HORAS, VALOR FROM CURSOS C
	WHERE C.NOME = NOME;
END

CALL CONSULTA_CURSO('JAVAA');

CREATE PROCEDURE CONSULTA_CURSO_2(NOME VARCHAR(30))
BEGIN
	SELECT ID_CURSO, NOME, HORAS, VALOR FROM CURSOS C
	WHERE C.NOME LIKE NOME;
END

CALL CONSULTA_CURSO_2('JAVA');

CREATE PROCEDURE CONSULTA_CURSO_3(NOME VARCHAR(30))
BEGIN
	SELECT ID_CURSO, C.NOME, HORAS, VALOR FROM CURSOS C
	WHERE C.NOME LIKE CONCAT('%', NOME, '%');
END

CALL CONSULTA_CURSO_3('A');

CREATE PROCEDURE CONSULTA_CURSO_4(NOME VARCHAR(30), HORAS INT(3))
BEGIN
	SELECT ID_CURSO, C.NOME, C.HORAS, C.VALOR FROM CURSOS C
	WHERE C.NOME LIKE CONCAT('%', NOME, '%')
	AND C.HORAS >= IFNULL(HORAS, 0);
END

CALL CONSULTA_CURSO_4('BI', 30);

CREATE PROCEDURE CONSULTA_CURSO_5(NOME VARCHAR(30), HORAS INT(3), VALOR FLOAT(10,2))
BEGIN
	SELECT C.ID_CURSO, C.NOME, C.HORAS, C.VALOR FROM CURSOS C
	WHERE C.NOME LIKE CONCAT('%', IFNULL(NOME, ''), '%')
	AND C.HORAS >= IFNULL(HORAS, 0)
	AND C.VALOR >= IFNULL(VALOR, 0);
END

CALL CONSULTA_CURSO_5('BI', 35, 1000);