SHOW DATABASES;

-- CRIANDO TABELAS

CREATE DATABASE MECANICA;

USE MECANICA;

SHOW TABLES;

CREATE TABLE CLIENTE(
	IDCLIENTE INT AUTO_INCREMENT,
	NOME VARCHAR(10) NOT NULL,
	SEXO ENUM('F', 'M') NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE)
);

ALTER TABLE CLIENTE;

DESC CLIENTE;

CREATE TABLE MARCA(
	IDMARCA INT AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY (IDMARCA),
	CONSTRAINT UK_MARCA_NOME UNIQUE (NOME)
);

DESC MARCA;

CREATE TABLE TELEFONE(
	IDTELEFONE INT AUTO_INCREMENT,
	NUMERO VARCHAR(11) NOT NULL,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT PK_TELEFONE PRIMARY KEY (IDTELEFONE),
	CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	CONSTRAINT UK_TELEFONE_NUMERO UNIQUE (NUMERO)
);

DESC TELEFONE;

CREATE TABLE CARRO(
	IDCARRO INT AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	ANO INT(4) NOT NULL,
	PLACA CHAR(7) NOT NULL,
	ID_MARCA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT PK_CARRO PRIMARY KEY (IDCARRO),
	CONSTRAINT FK_CARRO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDMARCA),
	CONSTRAINT FK_CARRO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	CONSTRAINT UK_CARRO_PLACA UNIQUE (PLACA),
	CONSTRAINT UK_CARRO_ID_CLIENTE UNIQUE (ID_CLIENTE)
);

DESC CARRO;

CREATE TABLE COR(
	IDCOR INT AUTO_INCREMENT,
	DESCRICAO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_COR PRIMARY KEY (IDCOR),
	CONSTRAINT UK_COR_DESCRICAO UNIQUE(DESCRICAO)
);

DESC COR;

CREATE TABLE COR_CARRO(
	ID_CARRO INT NOT NULL,
	ID_COR INT NOT NULL,
	CONSTRAINT PR_COR_CARRO PRIMARY KEY(ID_CARRO, ID_COR)
);

DESC COR_CARRO;

SHOW TABLES;

INSERT INTO MARCA
VALUES 
(NULL, 'VOLKSWAGEN'),
(NULL, 'FORD'),
(NULL, 'CHEVROLET'),
(NULL, 'FIAT'),
(NULL, 'CITROEN'),
(NULL, 'PORCHE'),
(NULL, 'BUGATTI'),
(NULL, 'CADILAC'),
(NULL, 'BMW'),
(NULL, 'GURGEL'),
(NULL, 'TIGGO');

SELECT * FROM MARCA
ORDER BY 2;

INSERT INTO COR
VALUES
(NULL, 'PRETO'),
(NULL, 'BRANCO'),
(NULL, 'VERDE'),
(NULL, 'AZUL'),
(NULL, 'AMARELO'),
(NULL, 'VERMELHO'),
(NULL, 'ROSA'),
(NULL, 'PRATA'),
(NULL, 'BEGE');

SELECT * FROM COR;

DROP TABLE CLIENTE;

INSERT INTO CLIENTE
VALUES
(NULL, 'ANA', 'F'),
(NULL, 'BIANCA', 'F'),
(NULL, 'CARLOS', 'M'),
(NULL, 'DANIEL', 'M'),
(NULL, 'EMELLY', 'F'),
(NULL, 'FAUSTO', 'M'),
(NULL, 'GABRIEL', 'M'),
(NULL, 'HOJE', 'M'),
(NULL, 'IONE', 'F'),
(NULL, 'JULIETTE', 'F'),
(NULL, 'KARINE', 'F'),
(NULL, 'LUIS', 'M');

SELECT * FROM CLIENTE;

INSERT INTO
    CARRO
VALUES
    (NULL, 'M3', 2005, 'ABC9876', 9, 1),
    (NULL, 'VERON', 2014, 'BUG1680', 7, 2),
    (NULL, 'ESCALAD', 2005, 'ESC2005', 8, 3),
    (NULL, 'PRIMA', 2014, 'GMS4544', 3, 4),
    (NULL, 'C3', 2001, 'CTE9578', 5, 5),
    (NULL, 'UNO', 1984, 'FIA1477', 4, 6),
    (NULL, 'GT2', 2010, 'POR9112', 6, 7),
    (NULL, 'TIGGO 7', 2020, 'TGO7777', 11, 8),
    (NULL, 'BR800', 2020, 'GUR8000', 10, 9),
    (NULL, 'FIESTA', 2020, 'FIE1234', 2, 10),
    (NULL, 'KA', 2020, 'KAA9658', 2, 11),
    (NULL, 'FUSCA', 1963, 'FSC1963', 1, 12);
   
INSERT INTO
    TELEFONE
VALUES
    (NULL, '24210000', 'RES', 1),
    (NULL, '33331234', 'COM', 2),
    (NULL, '987654321', 'CEL', 4),
    (NULL, '24210001', 'RES', 5),
    (NULL, '33331235', 'COM', 6),
    (NULL, '987654322', 'CEL', 7),
    (NULL, '24210002', 'RES', 8),
    (NULL, '33331236', 'COM', 9),
    (NULL, '987654323', 'CEL', 10),
    (NULL, '987654324', 'CEL', 11),
    (NULL, '24210003', 'RES', 12),
    (NULL, '987654325', 'CEL', 3);

SELECT * FROM TELEFONE T ;

SELECT * FROM CARRO C
INNER JOIN MARCA M ON M.IDMARCA = C.ID_MARCA
INNER JOIN CLIENTE CL ON CL.IDCLIENTE = C.ID_CLIENTE
ORDER BY 1;

INSERT INTO COR_CARRO
VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 1),
(11, 2),
(12, 3),
(11, 7),
(11, 3),
(11, 4),
(11, 5),
(12, 1),
(12, 2),
(12, 5);

SELECT * FROM COR_CARRO;

-- CARRO E COR
SELECT CA.MODELO AS CARRO, CO.DESCRICAO AS COR FROM COR_CARRO CC
INNER JOIN CARRO CA ON CA.IDCARRO = CC.ID_CARRO
INNER JOIN COR CO ON CO.IDCOR = CC.ID_COR
ORDER BY 1, 2;

-- TODOS OS DADOS
SELECT 
	CL.NOME
	, CL.SEXO
	, T.NUMERO AS 'TELEFONE'
	, T.TIPO AS 'TIPO TEL.'
	, M.NOME AS MARCA
	, CA.MODELO
	, CO.DESCRICAO AS COR
	, CA.ANO
	, CA.PLACA 
FROM COR_CARRO CC
INNER JOIN CARRO CA ON CA.IDCARRO = CC.ID_CARRO
INNER JOIN MARCA M ON M.IDMARCA = CA.ID_MARCA 
INNER JOIN COR CO ON CO.IDCOR = CC.ID_COR
INNER JOIN CLIENTE CL ON CL.IDCLIENTE = CA.ID_CLIENTE 
INNER JOIN TELEFONE T ON T.ID_CLIENTE = CL.IDCLIENTE
ORDER BY 1, CO.DESCRICAO ;

-- QUANTIDADE DE CORES
SELECT COUNT(*) AS QTD, CO.DESCRICAO AS COR FROM COR_CARRO CC
INNER JOIN COR CO ON CO.IDCOR = CC.ID_COR
GROUP BY CO.DESCRICAO 
ORDER BY 1 DESC;

-- QUANTIDADE DE CLIENTES POR SEXO
SELECT COUNT(*) TOTAL, SEXO FROM CLIENTE C
GROUP BY C.SEXO



USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS ;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
	   TABLE_NAME AS "TABELA",
	   CONSTRAINT_NAME AS "NOME DA REGRA",
	   CONSTRAINT_TYPE AS "TIPO"
FROM TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'MECANICA';