CREATE DATABASE AULA44;

USE AULA44;

CREATE TABLE CURSOS (
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY (ID_PREREQ) REFERENCES CURSOS(IDCURSO);

SHOW TABLES;

DESC CURSOS;

INSERT INTO CURSOS VALUES (NULL, 'SEM PRE REQ', 0, 0.0, NULL);

INSERT INTO CURSOS VALUES (NULL, 'BD RELACIONAL', 20, 400.0, NULL);
INSERT INTO CURSOS VALUES (NULL, 'BUSSNESS INTELLIGENCE', 40, 800.0, 2);
INSERT INTO CURSOS VALUES (NULL, 'RELATORIOS AVANCADOS', 20, 600.0, 3);
INSERT INTO CURSOS VALUES (NULL, 'LOGICA DE PROGRAMACAO', 20, 400.0, NULL);
INSERT INTO CURSOS VALUES (NULL, 'RUBY', 30, 500.0, 5);
INSERT INTO CURSOS VALUES (NULL, 'JAVA', 50, 700.0, 5);

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQUISITOS") FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQUISITOS") FROM CURSOS;

/* NOME, VALOR, HORAS E NOME DO PRE REQUISITO DO CURSO */

/* MINHA RESPOSTA */
SELECT 
		NOME
		, VALOR
		, HORAS
		, IFNULL(
			(SELECT P.NOME FROM CURSOS P WHERE P.IDCURSO = C.ID_PREREQ)
			, "---"
		) AS PREREQ 
FROM CURSOS C;

/* RESPOSTA DO PROFESSOR */
SELECT 
C.NOME AS CURSO, 
C.VALOR AS VALOR,
C.HORAS AS CARGA,
IFNULL(P.NOME, '---') AS PREREQ
FROM CURSOS C
/*LEFT JOIN PARA TRAZER TODOS OS CURSOS, INCLUSIVE OS QUE NÃO TEM PREREQ*/
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;