SHOW DATABASES;

USE COMERCIO;

SELECT 
	C.NOME, 
	IFNULL(C.EMAIL, '**********') AS "E-MAIL", 
	E.ESTADO, 
	T.NUMERO 
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE ;

/* VIEW */

SELECT 
	C.NOME, 
	C.SEXO, 
	C.EMAIL, 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

CREATE VIEW RELATORIO AS 
SELECT 
	C.NOME, 
	C.SEXO, 
	C.EMAIL, 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM RELATORIO;

SHOW TABLES;
SHOW DATABASES;
SHOW VIEWS; -- NÃO EXISTE

/* APAGANDO UMA VIEW */

DROP VIEW V_RELATORIO;

/* INSERINDO UM PREFIXO */
CREATE VIEW V_RELATORIO AS 
SELECT 
	C.NOME, 
	C.SEXO, 
	IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

SELECT * FROM V_RELATORIO;

/* UPDATE, INSERT E DELETE - DML */
INSERT INTO V_RELATORIO VALUES(
	'ANDREIA', 'F', 'ANDREIA@OUL.COM.BR', 'CEL', '87547864', 'CENTRO', 'VITORIA', 'ES'
);

DELETE FROM V_RELATORIO 
WHERE NOME = 'JORGE';

UPDATE V_RELATORIO 
SET NOME = 'JOSÉ'
WHERE NOME = 'JORGE';

/* INSERT E DELETE EM VIEW COM JOIN NÃO É PERMITIDO */

/* UPDATE EM VIEW COM JOIN É PERMITIDO */

SELECT * FROM CLIENTE c ;

/* VIEWS SÃO PONTEIROS, SE USAR O UPDATE, ELA ALTERA NA TABELA RAIZ */

SELECT * FROM V_RELATORIO vr ;

-- SQL Error [1394] [HY000]: Can not insert into join view 'COMERCIO.V_RELATORIO' without fields list

CREATE TABLE JOGADORES (
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);


INSERT INTO JOGADORES VALUES 
	(1, 'GUERRERO', 'RS'),
	(2, 'GABIGOL', 'RJ'),
	(3, 'GANSO', 'RJ'),
	(4, 'NENÊ', 'RJ'),
	(5, 'LOVE', 'SP');

SELECT * FROM JOGADORES;

ALTER VIEW V_JOGADORES AS
SELECT NOME, ESTADO FROM JOGADORES;

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

SELECT * FROM V_JOGADORES;

INSERT INTO V_JOGADORES  VALUES ('GUERRERO', 'RS');

SELECT * FROM V_JOGADORES;

SELECT * FROM JOGADORES;

SELECT * FROM V_RELATORIO V
WHERE V.SEXO = 'F';

/* ORDER BY */

CREATE TABLE ALUNOS (
	NUMERO INT,
	NOME VARCHAR(30)
);

SHOW TABLES;

INSERT INTO ALUNOS VALUES
	(1, 'JOAO'),
	(1, 'MARIA'),
	(2, 'ZOE'),
	(2, 'ANDRE'),
	(3, 'CLARA'),
	(1, 'CLARA'),
	(4, 'MAFRA'),
	(5, 'JANAINA'),
	(1, 'JANAINA'),
	(3, 'MARCELO'),
	(4, 'GIOVANI'),
	(5, 'ANTONIO'),
	(6, 'ANA'),
	(6, 'VIVIANE');

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1;

SELECT * FROM ALUNOS
ORDER BY 2;

/* ORDENANDO POR MAIS DE UMA COLUNA */
SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;

/* MESCLANDO ORDER BY COM PROJEÇÃO */
SELECT NOME FROM ALUNOS a 
ORDER BY 1,2;

SELECT NOME FROM ALUNOS a 
ORDER BY NUMERO, NOME;

/* ORDER BY DESC / ASC*/
SELECT * FROM ALUNOS a 
ORDER BY 1,2;

SELECT * FROM ALUNOS a 
ORDER BY 1 ASC;

SELECT * FROM ALUNOS a 
ORDER BY 1 DESC;

SELECT * FROM ALUNOS a 
ORDER BY 1, 2 DESC;

SELECT * FROM ALUNOS a 
ORDER BY 1 DESC, 2 DESC;

/* ORDENANDO COM OS JOINS */

SELECT 
	C.NOME, 
	C.SEXO, 
	IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
	T.TIPO, 
	T.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1 ;

SHOW TABLES;

SELECT * FROM V_RELATORIO vr 
ORDER BY 1;

SELECT * FROM V_RELATORIO vr 
ORDER BY 1 DESC;