-- ENTENDENDO TRIGGERS
/* ESTRUTURA DE UMA TRIGGER */

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (CADA LINHA)
BEGIN -> INICIO

END -> FIM

USE INFORMATION_SCHEMA;

DESC TRIGGERS ;

SELECT * FROM TRIGGERS t ;

CREATE DATABASE AULA40;

USE AULA40;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO 
	VALUES (NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END

INSERT INTO USUARIO VALUES(NULL, 'ANDRADE', 'ANDRADE2009', 'HEXACAMPEAO');

SELECT * FROM USUARIO;

DELETE FROM USUARIO
WHERE IDUSUARIO = 1;

SELECT * FROM BKP_USUARIO;

/* COMUNICACAO ENTRE BANCOS */

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);


CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
); 

USE LOJA;

INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, 1000, 'TESTE', 0.0);

SELECT * FROM BACKUP.BKP_PRODUTO;

CREATE TRIGGER BACKUP_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES
		(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);
	
END

INSERT INTO PRODUTO 
	VALUES
(NULL, 'LIVRO MODELAGEM', 50.0),
(NULL, 'LIVRO BI', 80.0),
(NULL, 'LIVRO ORACLE', 70.0),
(NULL, 'LIVRO SQL SERVER', 100.0);

SELECT * FROM PRODUTO;

SELECT * FROM BACKUP.BKP_PRODUTO;

CREATE TRIGGER BACKUP_PRODUTO_DELETE
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES
		(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR);
	
END

DELETE FROM PRODUTO
WHERE IDPRODUTO = 2;

SELECT * FROM BACKUP.BKP_PRODUTO;

DROP TRIGGER BACKUP_PRODUTO;

CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES
		(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR);
	
END

INSERT INTO PRODUTO VALUES (NULL, 'LIVRO DE C#', 100.0);

SELECT * FROM PRODUTO;

SELECT * FROM BACKUP.BKP_PRODUTO;

ALTER TABLE BACKUP.BKP_PRODUTO 
ADD COLUMN EVENTO CHAR(1);

SELECT * FROM BACKUP.BKP_PRODUTO;

USE LOJA;

DROP TRIGGER BACKUP_PRODUTO_DELETE; 

CREATE TRIGGER BACKUP_PRODUTO_DELETE
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES
		(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, 'D');
	
END;

SHOW TABLES;

SELECT * FROM PRODUTO p ;

DELETE FROM PRODUTO 
WHERE IDPRODUTO = 4;

SELECT * FROM BACKUP.BKP_PRODUTO;

DROP DATABASE BACKUP;

DROP DATABASE LOJA;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

SHOW TABLES;

DROP TABLE BKP_PRODUTO;

INSERT INTO PRODUTO 
	VALUES
(NULL, 'LIVRO MODELAGEM', 50.0),
(NULL, 'LIVRO BI', 80.0),
(NULL, 'LIVRO ORACLE', 70.0),
(NULL, 'LIVRO SQL SERVER', 100.0);

CREATE DATABASE BACKUP;

USE BACKUP;

/* QUANDO */
SELECT NOW();

/* QUEM */
SELECT CURRENT_USER();

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	BKP_PRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

SHOW TABLES;

DROP TABLE BKP_PRODUTO;

USE LOJA;

SHOW TABLES;

SELECT * FROM PRODUTO;

CREATE TRIGGER AUDIT_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN 
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES
		(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U' );
	
END;

SELECT * FROM PRODUTO p ;

UPDATE PRODUTO 
SET VALOR = 110
WHERE IDPRODUTO = 4;

SELECT * FROM BACKUP.BKP_PRODUTO bp ;