DROP DATABASE COMERCIO;

CREATE DATABASE COMERCIO;

USE COMERCIO;

SELECT * FROM CLIENTE;

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO char(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);

SHOW TABLES;

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF) VALUES
	 ('JOAO','M','JOAO@IG.COM','12345678945'),
	 ('CARLOS','M','CARLOS@IG.COM','34589672631'),
	 ('ANA','F','ANA@IG.COM','487965874123'),
	 ('CLARA','F',NULL,'986248635798'),
	 ('JORGE','M','JORGE@IG.COM','12647954785'),
	 ('CELIA','F','CELIA@IG.COM','65894236871'),
	 ('PAULA','F',NULL,'987456589');
	
INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF) VALUES 	 ('FLAVIO','M','FLAVIO@IG.COM','4657765');

DELETE FROM CLIENTE
WHERE IDCLIENTE = 8;

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF) VALUES
	 ('FLAVIO','M','FLAVIO@IG.COM','4657765'),
	 ('ANDRE','M','ANDRE@GLOBO.COM','7687567'),
	 ('GIOVANA','F',NULL,'0876655'),
	 ('KARLA','M','KARLA@GMAIL.COM','545676778'),
	 ('DANIELE','M','DANIELE@GMAIL.COM','43536789'),
	 ('LORENA','M',NULL,'774557887'),
	 ('EDUARDO','M',NULL,'54376457'),
	 ('ANTONIO','F','ANTONIO@IG.COM','12436767'),
	 ('ANTONIO','M','ANTONIO@UOL.COM','3423565'),
	 ('ELAINE','M','ELAINE@GLOBO.COM','32567763'),
	 ('CARMEM','M','CARMEM@IG.COM','787832213'),
	 ('ADRIANA','F','ADRIANA@GMAIL.COM','88556942'),
	 ('JOICE','F','JOICE@GMAIL.COM','55412256');
	
SELECT * FROM CLIENTE;

INSERT INTO TELEFONE (TIPO,NUMERO,ID_CLIENTE) VALUES
	 ('CEL','78458743',5),
	 ('RES','56565565',5),
	 ('CEL','12345689',1),
	 ('COM','12387933',2),
	 ('RES','12487963',1),
	 ('CEL','15489963',3),
	 ('CEL','48996632',3),
	 ('COM','78332459',1),
	 ('RES','12345678',5),
	 ('CEL','98746622',2);
	
INSERT INTO
	TELEFONE
VALUES
(NULL, 'CEL', '99656675', 9),
	(NULL, 'CEL', '33567765', 11),
	(NULL, 'CEL', '88668786', 11),
	(NULL, 'COM', '55689654', 11),
	(NULL, 'COM', '88687979', 12),
	(NULL, 'COM', '88965676', 13),
	(NULL, 'CEL', '89966809', 15),
	(NULL, 'COM', '88679978', 16),
	(NULL, 'CEL', '99655768', 17),
	(NULL, 'RES', '89955665', 18),
	(NULL, 'RES', '77455786', 19),
	(NULL, 'RES', '89766554', 19),
	(NULL, 'RES', '77755785', 20),
	(NULL, 'COM', '44522578', 20);

UPDATE TELEFONE 
SET ID_CLIENTE = 21
WHERE IDTELEFONE = 24;


SELECT * FROM TELEFONE t ;

INSERT INTO ENDERECO (RUA,BAIRRO,CIDADE,ESTADO,ID_CLIENTE) VALUES
	 ('RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4),
	 ('RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1),
	 ('RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3),
	 ('RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2),
	 ('RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6),
	 ('RUA URUGUAIANA','CENTRO','VITORIA','ES',5),
	 ('RUA JOAQUIM SILVA','ALVORADA','NOTEROI','RJ',7);
	
INSERT INTO ENDERECO VALUES
(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9),
(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10),
(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11),
(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12),
(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13),
(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14),
(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15),
(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16),
(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17),
(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18),
(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19),
(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20),
(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

SELECT * FROM ENDERECO e ;

/* EXERCICIOS DML */

/* RELATORIO GERAL DE TODOS OS CLIENTES */

DESC CLIENTE ;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO 
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON E.ID_CLIENTE = C.IDCLIENTE 
	INNER JOIN TELEFONE T
	ON T.IDTELEFONE = C.IDCLIENTE ;

/* RELATORIO DE HOMENS */
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO 
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON E.ID_CLIENTE = C.IDCLIENTE 
	INNER JOIN TELEFONE T
	ON T.IDTELEFONE = C.IDCLIENTE 
WHERE C.SEXO = 'M';

/* 12, 13, 14, 18 E 19 */
SELECT * FROM CLIENTE C 
WHERE IDCLIENTE IN (12,13,14,18,19);

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (12,13,14,18,19);

/* RELATORIO DE MULHERES */
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON T.IDTELEFONE = C.IDCLIENTE 
	INNER JOIN ENDERECO E
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE C.SEXO = 'F';

/* 16 */
SELECT * FROM CLIENTE C 
WHERE IDCLIENTE = 16;

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 16;

/* QUANTIDADE DE HOMENS E MULHERES */
SELECT C.SEXO, COUNT(*) AS QUANTIDADE 
FROM CLIENTE C 
GROUP BY C.SEXO ;

/* IDS E EMAIL DAS MULHER QUE MOREM NO CENTRO DO 
   RIO DE JANEIRO E NÃO TENHAM CELULAR */
SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE 
FROM CLIENTE C
	INNER JOIN TELEFONE T 
	ON T.ID_CLIENTE = C.IDCLIENTE
	INNER JOIN ENDERECO E 
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE SEXO = 'F';

SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE 
FROM CLIENTE C
	INNER JOIN TELEFONE T 
	ON T.ID_CLIENTE = C.IDCLIENTE
	INNER JOIN ENDERECO E 
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE SEXO = 'F'
AND E.BAIRRO = 'CENTRO'
AND E.CIDADE = 'RIO DE JANEIRO';

SELECT C.IDCLIENTE, C.EMAIL 
FROM CLIENTE C
	INNER JOIN TELEFONE T 
	ON T.ID_CLIENTE = C.IDCLIENTE
	INNER JOIN ENDERECO E 
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE SEXO = 'F'
AND E.BAIRRO = 'CENTRO'
AND E.CIDADE = 'RIO DE JANEIRO'
AND T.TIPO <> 'CEL';

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATORIO COM NOME, EMAIL E TELEFONE CELULAR
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA
O PROGRAMADOR
*/
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
	INNER JOIN TELEFONE T 
	ON T.ID_CLIENTE = C.IDCLIENTE
	INNER JOIN ENDERECO E 
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE T.TIPO = 'CEL'
AND E.ESTADO = 'RJ';

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO
VOCÊ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA
O PROGRAMADOR
*/
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
	INNER JOIN TELEFONE T 
	ON T.ID_CLIENTE = C.IDCLIENTE
	INNER JOIN ENDERECO E 
	ON E.ID_CLIENTE = C.IDCLIENTE 
WHERE C.SEXO = 'F'
AND E.ESTADO = 'SP'
AND T.TIPO = 'CEL';