/* PROCEDURES */
/* SP - STORAGE PROCEDURES */

USE EMPRESA
GO

CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN ('M', 'F')),
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE (
	IDTELEFONE INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK(TIPO IN ('CEL', 'COM')),
	NUMERO VARCHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES ('ANTONIO', 'M', '1981-02-13')
INSERT INTO PESSOA VALUES ('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES ('CLEIDE', 'F', '1979-10-13')


INSERT INTO TELEFONE VALUES ('CEL', '98790008', 1)
INSERT INTO TELEFONE VALUES ('COM', '87597909', 1)
INSERT INTO TELEFONE VALUES ('CEL', '98755890', 2)
INSERT INTO TELEFONE VALUES ('CEL', '99347689', 2)
INSERT INTO TELEFONE VALUES ('COM', '19988689', 3)
INSERT INTO TELEFONE VALUES ('COM', '20988978', 2)
INSERT INTO TELEFONE VALUES ('CEL', '90008679', 3)
GO

/* CRIANDO PROCEDURE */

CREATE PROC SOMA
AS
	SELECT 10 + 11 AS SOMA
GO

/* EXECUTANDO PROCEDURE */
EXEC SOMA
GO

/* DINAMICAS COM PARAMETROS */

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2
GO

/* EXECUTANDO */

EXEC CONTA 90,78
GO

/* APAGANDO A PROCEDURE */

DROP PROC CONTA
GO

/* PROCEDURES EM TABELAS */

SELECT NOME, NUMERO 
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/* TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO */
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO 
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO

GO

EXEC TELEFONES 'CEL' 
GO 

EXEC TELEFONES 'COM' 
GO 

/* PARAMETROS DE OUTPUT */

SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

/* CRIANDO PROCEDURES COM PARAMETROS DE ENTRADA E SAIDA */
CREATE PROCEDURE GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
	GO
	
/* EXECUTANDO PROCUREDE COM PARAMETRO DE SAÍDA */
	
/* TRANSACTION SQL-> LINGUAGEM QUE O SQL SERVER TRABALHA */
	
DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT 
SELECT @SAIDA
GO

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @SAIDA OUTPUT 
SELECT @SAIDA
GO

INSERT INTO PESSOA VALUES ('MAFRA', 'M', '1981-02-13')

SELECT @@IDENTITY -- GUARDA O ÚLTIMO ID INSERIDO NA SEÇÃO

DROP PROCEDURE CADASTRO GO

/* PROCEDURE DE CADASTRO */
CREATE PROCEDURE CADASTRO 
@NOME VARCHAR(30),
@SEXO CHAR(1),
@NASCIMENTO DATE,
@TIPO CHAR(3),
@NUMERO VARCHAR(10)
AS
	DECLARE @FK INT
	
	INSERT INTO PESSOA VALUES (@NOME, @SEXO, @NASCIMENTO)
	
	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)
	
	INSERT INTO TELEFONE VALUES (@TIPO, @NUMERO, @FK)
	GO

EXEC CADASTRO 'DANIEL', 'M', '1996-02-15', 'CEL', '986284900'
GO

SELECT PESSOA.*, TELEFONE.* FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO