/* SELECIONANDO BANCO DE DADOS */
USE LIVRARIA;

/* OPERADORES LÓGICOS*/

/*USANDO OPERADORES LÓGICOS*/
SELECT NOME_AUTOR, SEXO_AUTOR 
FROM LIVROS
WHERE SEXO_AUTOR = 'M'
AND ESTADO_EDITORA IN ('SP', 'RJ');

/*VERIFICANDO*/
SELECT NOME_AUTOR, SEXO_AUTOR, ESTADO_EDITORA 
FROM LIVROS
WHERE SEXO_AUTOR = 'M'
AND (
	ESTADO_EDITORA = 'SP' OR ESTADO_EDITORA = 'RJ'
);

/* 
OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA UE APENAS UMA CONDICAO SEJA VERDADEIRA 
AND -> PARA QUE SAIDA SEJA SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRAS */

/* MOSTRA OS BANCOS*/
SHOW DATABASES;

/*SELECIONANDO BANCO*/
USE PROJETO;

/*MOSTRANDO TABELAS*/
SHOW TABLES;

/* OR */
SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND */
SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY COM OPERADORES LOGICOS */

/* CONTAOD OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS "Quantidade de Registro da Tab. Cliente" 
FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO ;

/* PERFORMANCE EM OPERADORES LOGICOS */

/* 1 MILHAO DE REGISTROS 
 * PARA CONTAR */

SELECT COUNT (*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM CLIENTE
GROUP BY ENDERECO;

/*CONDICAO
SEXO = 'F'
CIDADE = 'RIO DE JANEIRO'*/

/* SITUACAO - TRATANDO COM OU / OR 
70% MULHER = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR ENDERECO LIKE '%RIO DE JANEIRO%';