CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES 
	(NULL, 'MAFRA', 32432, 24233, 57454),
	(NULL, 'CLARA', 54689, 98765, 12345),
	(NULL, 'JOAO', 45698, 12398, 78945),
	(NULL, 'LILIAN', 58256, 12369, 15975),
	(NULL, 'ANTONIO', 74125, 89630, 10203),
	(NULL, 'GLORIA', 33333, 70809, 40506);
	
SELECT * FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL, (JAN + FEV + MAR) / 3 AS MEDIA FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	DECLARE REG CURSOR FOR(
		SELECT NOME, JAV, FEV, MAR FROM VENDEDORES
	);

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	OPEN REG;

	REPEAT
	
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			
			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;
			INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		
		END IF;
	
	UNTIL FIM END REPEAT;

	CLOSE REG;
	
END

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();